* 华星顺丰月结号：5121152069
* Dark Souls 3
| 洋葱剑士的酒 | 太阳战士铠甲       |
| 雷壶         | 铁之头盔           |
| 返回骨片     | 铁之臂架           |
| 巨人的果实   | 铁之腿甲           |
| 圣职者的圣铃 | 人面语『救救我』   |
| 丧失石       | 人面语『我很抱歉』 |
| 引诱的头盖骨 | 人面语『你好』     |
| 秘藏的祝福   | 人面语『谢谢』     |
| 女神的祝福   | 人面语『很好』     |
| 火焰壶       | 楔形石大碎片       |
| 黑火焰壶     | 楔形石块           |
| 螺旋剑的破片 | 楔形石原盘         |
| 七色石       | 光之楔形石         |
| 黄衣头冠     | 雷之贵石           |
| 不死的遗骨   | 隸兽之盾           |
| 枷之椎骨     | 卢卡提耶的面具     |
** 1、做洋葱骑士的支线任务。
①在主线流程中我们会在不死镇射箭巨人的高塔里见到洋葱骑士。刷新地图后乘电梯上行过程中跳到一块木板上会进入新区域，见到洋葱并和他一起打死恶魔，算是完成第一步。
②攻克掉幽邃教堂boss，幽邃主教群后，在净身小教会门口的井中会发现求救的洋葱，此处一定要救他。去找帕奇买一套洋葱盔甲丢给他就算了事。(帕奇除了会穿洋葱套在幽邃教堂阴你，还会在火鸡场的防火女墓塔里摆你一道，出来后和他对话选不原谅，会得到斑斓金币，数量稀有，先到先得)
③伊露西尔 正常走路线穿过下水道会遇到洋葱，和他一起哈皮后他会睡觉。此处还和小偷剧情有关。当你到达伊露西尔，小偷会请缨去偷东西，若是不和洋葱联动，小偷会死。此处和洋葱对完话后，不要去开地下监牢的篝火，这样洋葱就不会转移到地下监牢。打完法王后，会发现小偷已经回到火鸡场，和他对话会说洋葱救了他。
④罪恶之都 从罪都篝火的右边走会到一个满是贞子和毒谭的地方，爬上屋顶和一个魔法师对战后会发现对面墙上有一个小洞，跳进去找到关押洋葱的监牢，此处的监牢钥匙在地下监狱一个有咒娃的地方可以找到，藏在宝箱怪里。救出后洋葱会表示感谢送你一块圆盘。
** 2、在古龙顶可获得两块。
要想去古龙顶需先去洛斯里克城，进妖王庭院，杀死妖王在其门后深处有一个龙血骑士，可习得动作古龙之道。在地下监牢可找到一处有小龙人以及几个骑士的地方，做出古龙之道姿势，即可进入古龙顶。
在龙顶击杀无名后探索篝火地区，在不远处可捡到一块。
** 3、在受到飞龙袭击的地方
(不是古老飞龙，第二个龙)上方可见到哈维尔，旁边有第三块。
** 4、大书库
二楼正对阳台的俩个书架中间有一个机关，开启后，在一楼会打开一个隐藏区域，从宝箱中捡到第四块。(注意上蜡防诅咒)。
** 5、通过大书库到达最上层
会见到三只羽翼骑士，击杀，第五块。可以考虑在此刷魂。
** 6、在boss洛斯里克双王子门前右边有一处电梯
下去后会发现来到打猎龙铠甲的门前，其实此处和初见洋葱一样，是双层电梯，下去后会找到第六块。
** 7、在打薪王化身前找祭祀场老太婆，她会卖第七块。
** 8、在祭祀场鸟巢可用螺旋剑碎片换第八块。
** DLC1
第一个圆盘位置：
有螃蟹的哪里爬上楼梯有一个捡。建议从谷底篝火往上跑。
第二个圆盘位置：
修女boss过二阶段自动获得。
第三个圆盘位置：
鸦村碰到的一个善意NPC，打完修女boss，再与其对话，NPC会给。
** DLC2

1、两种获得方法 a.第二次见到拉普的篝火他会告诉你沼泽有宝物，来回传送几次后他会直接送给你  b.自己去沼泽的山洞里面拿，里面有一个胖子怪看守。
2、教堂骑士boss流程给一个。
3、也是两种方法。a、触碰公主的花瓶前完成黑龙击杀，回去环城的小房间跟希拉对话，他说谢谢你并赠送圆盘。b、触碰公主花瓶后出门右转，有一个圆型建筑，走到最里面会触发希拉入侵，打死以后获得武器和圆盘。
4、公主房间2出来后靠左边走，绕过墙后有个拿对剑环骑士，杀死后获得。
* Josephse
对于一个长度为7的环，我们走的步长是4。在走过4步之后我们找到3这个元素，并将它出队。然后我们在3后面的元素，4开始继续下一个查找步骤。而实际上我们从这个时候开始，不正是从n-1个元素里开始取元素了吗？因此我们可以将这个下一步取元素的问题归结为从n-1个元素里取下一个。不过，在上面的示例中，我们是在走到应该为4的元素那里重新以元素0开始作为n-1个元素取下一个的基础。因此，他们之间还存在着一个转换的关系。
    我们再从一个更加一般的场景来考虑。在第一个人出队之后，这个第一个出队的人的编号必然为(m - 1) % n。剩下的n-1个人组成一个新的Josephus环。只是这个时候我们是以m %  n开始。假定k = m % n。他们组成一个这样的序列：
    k, k+1, k+2...n-2, n-1, 0, 1, ... k-2。这个序列中缺少的k-1恰好就是我们前面一次遍历的时候找到并移除的。在我们将他们归结为n-1规模的Josephus环时，我们对他们有了这么一个映射：
       k --> 0
k+1 --> 1
k+2 --> 2
...
...
k-3 --> n-3
k-2 --> n-2
    这说明了一个什么问题呢？这说明对于我们在n-1的环中，任何一个元素的index对应到n的环中时他们之间差了k，也就是m % n。而这里的差不是一个简单的小于，而是由于整个环的结构，相当于一个循环进位的效果。这样，既然我们在n - 1对应到n的环中间是差了m % n，在更加一般的情况下，任何一个长度为l的环的元素对应到l +1的环的index都是差了这么个m % l。
    现在到了问题的关键点了。我们在一个n长的环里取m的步长，然后这个环里少了一个。剩下的n-1个元素构成了n-1环。而这里的元素和n长的元素之间的映射关系是Index(n) = (Index(n - 1) + m) % n。而如果我们载往下一步移除元素呢，他们之间的关系则是Index(n - 1) = (Index(n - 2) + m) % (n - 1)。哈哈，有意思，我们好像找到点规律了。没错，按照刚才的过程，我们这样一直移除元素下去，肯定能够找到最后一个被移除的元素。这个元素则对应只有一个元素的环，很显然，它的值为0。也就是Index(1) = 0。对于这个元素的索引，它对应两个元素的索引是多少呢？按照前面的过程，我们倒推回去就是了。Index(2) = (Index(1) + m) % 2。那么对应3个，4个元素的呢？我们这样一路继续下去就可以找到对应到n个元素的索引了。所以，我们发现了一个有意思的数学归纳关系：
f(1) = 0,  f(n) = (f(n - 1) + m) % n。

来自 <http://shmilyaw-hotmail-com.iteye.com/blog/2005438> 

* sscanf
sscanf的高级用法（总结） 

 sscanf(recvbuf,"%*[^/]/%[^ ]s",buf_rev); 
 sscanf(buf, "GET /%[^ ]", buf_rev);

 
这个是在一个webserver.c里面的例子，通过sscanf（）语句可以找到和它前面相匹配的语句然后打印出后面需要的东西，下面说下%[]:
其基本格式为 %[set]，表示将接收一个由set指定格式的字符串，其中set表示可接受的字符集合。
   set一般有两种情况：
                一种是"^set"表示非, 即在输入的字符串中将匹配所有不在set中出现的字符，
          遇到set中的字符时停止匹配。
                另一种是"set"表示在输入的字符串中将匹配所有在set中出现的字符，
          遇到非set中的字符时停止匹配。
 如：
 scanf("%[^&]",buf); //当输入的字符中出现"&"时停止匹配,如果输入hello&world,则buf=hello;
 scanf("%[^290#*]",buf); //当输入aidc＃ad时,则buf=aidc,
       即当输入出现了"#"时不再将输入内容放入buf
 scanf("%[dlza#i]",buf);//只匹配"dlza#i"这几个字符，
       如果不是这几个字符则停止匹配，如当输入ai＃dcad时,buf=ai#d,因为c不在[dlza#i]中.
 
特殊情况:
   (1)如果要匹配"^"时,当然不能直接放在[]中,所以可以用%[ab^cd]这种方式,
   (2)当要匹配右方括号"]"时,应把其放在set中第一个位置，如"%[]abc]"表示匹配的字符集为{], a, b, c}，又如"%[^]abc]"表示匹配所有非"], a, b, c"中的字符
   另外,还可以使用"-" 如%[a-z]表示只匹配abcd....yz等小写的字母;
   %[0-9]表示只匹配0,1,2...9等数字;
  (3) * 表示跳过，如：
int main()
{
 char buf[100]="123:asdfasd:2342342:liman:host:34234:hello";
 char user[20]="";
 char host[20]="";
 char msg[20]="";
 int cmd = 0;
 sscanf(buf, "%*d:%*[^:]:%*[^:]:%[^:]:%[^:]:%d:%s", user, host, &cmd, msg);
 return 0;
}
结果：user="liman",host="host",cmd=34234,msg=hello
    注意，“-”的字符只有在其左右两边都有有效字符时才有这个作用，否则被认为是普通字符，如“a-c-e-g”匹配的字符为｛a, b, c, -, e, f, g｝，这样也为输入“-”字符提供了方法。
sscanf函数的高级用法
sscanf与scanf类似，都是用于输入的，只是后者以屏幕(stdin)为输入源，前者以固定字符串为输入源。
函数原型：
int scanf( const char *format [,argument]... );
其中的format可以是一个或多个：
{%[*][width][{h|l|I64|L}]type|' '|'\t'|'\n'|非%符号}，
注：
1)、 * 亦可用于格式中, (即 %*d 和 %*s) 加了星号 (*) 表示跳过此数据不读入。
 (也就是不把此数据读入参数中)
2)、{a|b|c}表示a,b,c中选一，[d],表示可以有d也可以没有d。
3）、width:宽度，一般可以忽略，用法如：
const  char sourceStr[] = "hello, world";
char buf[10] = {0};
sscanf(sourceStr, "%5s", buf);   //%5s，只取5个字符
cout << buf<< endl;
结果为:hello
4）、{h|I|I64|L}:参数的size,通常h表示单字节size，I表示2字节 size,
  L表示4字节size(double例外),l64表示8字节size。
5）、type :这就很多了，就是%s,%d之类。
6）、特别的：%*[width] [{h|l|I64|L}]type 表示满足该条件的被过滤掉，
 不会向目标参数中写入值。如：
const char sourceStr[] = "hello, world";
char  buf[10] = {0};
sscanf(sourceStr, "%*s%s", buf);
//%*s表示第一个匹配到的%s被过滤掉，即hello被过滤了
cout << buf<< endl;
结果为:world
5）、支持集合操作：
%[a-z]  表示匹配a到z中任意字符，贪婪性(尽可能多的匹配)
%[aB']  匹配a、B、'中一员，贪婪性
%[^a]   匹配非a的任意字符，贪婪性
和正则表达式很相似，而且仍然支持过滤，即可以有%*[a-z]。
例子：
1. 常见用法。
char buf[512] = {0};
sscanf("123456 ", "%s", buf);
printf("%s\n", buf);
结果为：123456
2. 取指定长度的字符串。如在下例中，取最大长度为4字节的字符串。
    sscanf("123456 ", "%4s", buf);
 printf("%s\n", buf);
 结果为：1234
3. 取到指定字符为止的字符串。如在下例中，取遇到空格为止字符串。
    sscanf("123456 abcdedf", "%[^ ]", buf);
 printf("%s\n", buf);
 结果为：123456
4.  取仅包含指定字符集的字符串。如在下例中，取仅包含1到9和小写字母的字符串。
    sscanf("123456abcdedfBCDEF", "%[1-9a-z]", buf);
 printf("%s\n", buf);
 结果为：123456abcdedf
5.  取到指定字符集为止的字符串。如在下例中，取遇到大写字母为止的字符串。
    sscanf("123456abcdedfBCDEF", "%[^A-Z]", buf);
 printf("%s\n", buf);
 结果为：123456abcdedf
6、给定一个字符串iios/12DDWDFF@122，获取 / 和 @ 之间的字符串，
 先将 "iios/"过滤掉，再将非'@'的一串内容送到buf中
 sscanf("iios/12DDWDFF@122", "%*[^/]/%[^@]", buf);
 printf("%s\n", buf);
 结果为：12DDWDFF
7、给定一个字符串““hello, world”，仅保留world。（注意：“，”之后有一空格）
 sscanf(“hello, world”,  "%*s%s",  buf); 
 printf("%s\n", buf);
 结果为：world
 %*s表示第一个匹配到的%s被过滤掉，即hello被过滤了，如果没有空格则结果为NULL。
8、分隔字符串2006:03:18
 int a, b, c;
 sscanf("2006:03:18", "%d:%d:%d", a, b, c);
9、分隔字符串2006:03:18 - 2006:04:18
 char sztime1[16] = "", sztime2[16] = "";
 sscanf("2006:03:18 - 2006:04:18", "%s - %s", sztime1, sztime2);
10、分隔字符串2006:03:18-2006:04:18
 char sztime1[16] = "", sztime2[16] = "";
 sscanf("2006:03:18-2006:04:18", "%[0-9,:] - %[0-9,:]", sztime1, sztime2);
 仅仅是取消了‘-’两边的空格，却打破了%s对字符串的界定format-type中有%[]这样的type  field。如果读取的字符串，不是以空格来分隔的话，就可以使用%[]。%[]类似于一个正则表达式。 [a-z]表示读取a-z的所有字符，[^a-z]表示读取除a-z以外的所有字符。
 sscanf的功能很类似于正则表达式, 但却没有正则表达式强大,所以如果对于比较复杂的字符串处 理,建议使用正则表达式.
正则表达式的基本用法：
1、“.”为通配符，表示任何一个字符，例如：“a.c”可以匹配“anc”、“abc”、“acc”；
2、“[]”，在[]内可以指定要求匹配的字符，例如：“a[nbc]c”可以匹配“anc”、“abc”、"acc"；但不可以匹配“ancc”,a到z可以写成[a-z],0到9可以写成[0-9];
3、数量限定符号，表示匹配次数（或者叫做长度）的符号,包括：
“*”  0次或者多次
“+”  1次或者多次
“?”  0次或者1次
“{n}”    匹配n次，n为整数
“{n,m}”  匹配从n到m之间的某个数的次数；n和m都是整数；
“{n,}”   匹配n到无穷次之间任意次数；
“{,m}”   匹配0到m之间任意次数；
数量限定符号放到匹配格式的后面，例如：电话号码：024-84820482，02484820482(假设前面3或者4位，后面7或者8位，并且中间的减号可有可无)，都是符合规定的，那么可以用如下格式来匹配：[0-9]{3,4} \-? [0-9]{7,8}；注意：“\”为转义字符，因为“-”在正则表达式用有代表一个范围的意义，例如：前面所说的[0-9]，所以它需要转义字符“\”进行转义才可使用；
4、^为否符号，表示不想匹配的符号，例如：[^z][a-z]+可以匹配所有除"z"开头的以外的所有字
如果^放到[]的外边则表示以[]开头的字符串；^[az][a-z]+表示a或者z开头的长度大于等于2的英文字符串；
5、“|”或运算符，例如：a[n|bc|cb]c可以匹配“abcc”,“anc”,“acbc”；
6、“$”以它前面的字符结尾的；例如：ab+$就可以被“abb”，“ab”匹配；
7、一些简单表示方法：\d表示[0-9];\D表示[^0-9];\w表示[A-Z0-9];\W表示[^A-Z0-9];\s表示[\t\n\r\f],就是空格字符包括tab，空格等等;\S表示[^\t\n\r\f]，就是非空格字符;

* Work_related
** 华星工作相关
网络管理员相关：

无线网关及AC控制器
锐捷NBR1300G-E
管理IP地址：192.168.0.1
用户名：admin
密码：huaxing@2018!

上网WAN口设置
A：WAN3 ：静态IP （11楼电信猫内置拨号）
IP地址：192.168.1.66
子网掩码：255.255.255.0
网关：192.168.1.1
B：WAN4 ：静态IP
IP地址：58.210.95.110
子网掩码：255.255.255.252
网关：58.210.95.109


系统服务器：
IP地址：192.168.0.234
账户：administrator
密码：huaxing@2017




** 自用无线打印机密码是xurong123

** New Cell Phone

0、中行卡--工行卡
1、apple ID
2、taobao&支付宝&盒马  1个收货地址 1个账号信息
3、amazon 1个收货地址 1个账号信息
4、gmail ok
5、steam 和 battle.net cn 
New  15995677798

** 华明
网络位置：华明公共服务器
目标：\\192.168.0.5
用户名：sj610
密码：hm*12345

Xerox 打印机默认管理员识别符：11111  密码：x-admin

税务报备 32011
审计报告报备 500308

外汇申报 代码：746819717
	        用户：
0506060002
密码：
Hm123456

国家电网招标相关的PIN：szhm@1234

** 所得税
所得税申报：
伟速达：913205855511733623
密码：tc123456

联合年检&外汇年检
伟速达：3200551173362
密码：Vast123456*

* 驱蚊化学品：
避蚊胺（DEET）、
驱蚊酯（IR3535，伊莫宁）、
艾卡瑞丁、
柠檬桉叶油

* MIT Challenge

|   8.01: | Physics I - Classical Mechanics     | 2 weeks |
|  18.01: | Single Variable Calculus            | 2 weeks |
|  18.02: | Multi-Variable Calculus             | 2 weeks |
|   8.02: | Physics II- Electromagnetism        | 2 weeks |
|   6.01: | Introduction to EE and CS I         | 2 weeks |
|  5.111: | Principles of Chemical Science*     | 2 weeks |
|  7.012: | Introduction to Biology             | 2 weeks |
|  18.03: | Differential Equations              | 2 weeks |
|   6.02: | Introduction to EE and CS II        | 2 weeks |
| 6.042J: | Mathematics for Computer Science    | 2 weeks |
|  6.006: | Introduction to Algorithms          | 2 weeks |
|  18.06: | Linear Algebra                      | 2 weeks |
|  6.041: | Probabilistic Systems Analysis      | 2 weeks |
|  6.002: | Circuits and Electronics            | 2 weeks |
| 6.046J: | Design and Analysis of Algorithms   | 2 weeks |
|  6.034: | Artificial Intelligence             | 2 weeks |
|  6.003: | Signals and Systems                 | 2 weeks |
|  6.004: | Computation Structures              | 2 weeks |
| 24.241: | Logic I                             | 2 weeks |
|  14.01: | Principles of Microeconomics        | 2 weeks |
|  6.033: | Computer Systems Engineering        | 2 weeks |
|  6.013: | Electromagnetics and Applications   | 2 weeks |
|  14.02: | Principles of Macroeconomics        | 2 weeks |
| 24.242: | Logic II                            | 2 weeks |
|  6.011: | Intro to Comm., Control and Signals | 2 weeks |
| 24.244: | Modal Logic                         | 2 weeks |
|  14.20: | Industrial Organization             | 2 weeks |
|  14.23: | Government Regulation of Industry   | 2 weeks |
| 14.48J: | Economics of Education              | 2 weeks |
|  6.005: | Elements of Software Construction   | 2 weeks |
|  6.801: | Machine Vision                      | 2 weeks |
|  6.837: | Computer Graphics                   | 2 weeks |
| COSC 54 | 5: Theory of Computation            | 2 weeks |

* lisp 语言几大特性

    变量定义
    算术运算
    for 循环语句，while 循环语句
    函数定义，函数调用
    递归
    静态类型系统
    类型推导
    lambda 函数
    面向对象
    垃圾回收
    指针算术
    goto 语句

* 王垠的40行

;; A simple CPS transformer which does proper tail-call and does not
;; duplicate contexts for if-expressions.
;; author: Yin Wang (yw21@cs.indiana.edu)
(load "pmatch.scm")
(define cps
  (lambda (exp)
    (letrec
        ([trivial? (lambda (x) (memq x '(zero? add1 sub1)))]
         [id (lambda (v) v)]
         [ctx0 (lambda (v) `(k ,v))]      ; tail context
         [fv (let ([n -1])
               (lambda ()
                 (set! n (+ 1 n))
                 (string->symbol (string-append "v" (number->string n)))))]
         [cps1
          (lambda (exp ctx)
            (pmatch exp
              [,x (guard (not (pair? x))) (ctx x)]
              [(if ,test ,conseq ,alt)
               (cps1 test
                     (lambda (t)
                       (cond
                        [(memq ctx (list ctx0 id))
                         `(if ,t ,(cps1 conseq ctx) ,(cps1 alt ctx))]
                        [else
                         (let ([u (fv)])
                           `(let ([k (lambda (,u) ,(ctx u))])
                              (if ,t ,(cps1 conseq ctx0) ,(cps1 alt ctx0))))])))]
              [(lambda (,x) ,body)
               (ctx `(lambda (,x k) ,(cps1 body ctx0)))]
              [(,op ,a ,b)
               (cps1 a (lambda (v1)
                         (cps1 b (lambda (v2)
                                   (ctx `(,op ,v1 ,v2))))))]
              [(,rator ,rand)
               (cps1 rator
                     (lambda (r)
                       (cps1 rand
                             (lambda (d)
                               (cond
                                [(trivial? r) (ctx `(,r ,d))]
                                [(eq? ctx ctx0) `(,r ,d k)]  ; tail call
                                [else
                                 (let ([u (fv)])
                                   `(,r ,d (lambda (,u) ,(ctx u))))])))))]))])
      (cps1 exp id))))
;;; tests
;; var
(cps 'x)
(cps '(lambda (x) x))
(cps '(lambda (x) (x 1)))
;; no lambda (will generate identity functions to return to the toplevel)
(cps '(if (f x) a b))
(cps '(if x (f a) b))
;; if stand-alone (tail)
(cps '(lambda (x) (if (f x) a b)))
;; if inside if-test (non-tail)
(cps '(lambda (x) (if (if x (f a) b) c d)))
;; both branches are trivial, should do some more optimizations
(cps '(lambda (x) (if (if x (zero? a) b) c d)))
;; if inside if-branch (tail)
(cps '(lambda (x) (if t (if x (f a) b) c)))
;; if inside if-branch, but again inside another if-test (non-tail)
(cps '(lambda (x) (if (if t (if x (f a) b) c) e w)))
;; if as operand (non-tail)
(cps '(lambda (x) (h (if x (f a) b))))
;; if as operator (non-tail)
(cps '(lambda (x) ((if x (f g) h) c)))
;; why we need more than two names
(cps '(((f a) (g b)) ((f c) (g d))))
;; factorial
(define fact-cps
  (cps
   '(lambda (n)
      ((lambda (fact)
         ((fact fact) n))
       (lambda (fact)
         (lambda (n)
           (if (zero? n)
               1
               (* n ((fact fact) (sub1 n))))))))))
;; print out CPSed function
(pretty-print fact-cps)
;; =>
;; '(lambda (n k)
;;    ((lambda (fact k) (fact fact (lambda (v0) (v0 n k))))
;;     (lambda (fact k)
;;       (k
;;        (lambda (n k)
;;          (if (zero? n)
;;            (k 1)
;;            (fact
;;             fact
;;             (lambda (v1) (v1 (sub1 n) (lambda (v2) (k (* n v2))))))))))
;;     k))
((eval fact-cps) 5 (lambda (v) v))
;; => 120

来自 <https://www.zhihu.com/question/20822815> 

* 综合
你回头考了CPA，为了搞懂会计中的金融产品，你觉得有必要考一个CFA，后来你凭兴趣进入投行，常常需要统一不同国家财务报告的比较口径，这时你寻思着考AICPA & ACA，同时为了及时识别金融风险和法律风险，你认为FRM & 司法必不可少。整个探索的过程，数学如影随形，它让你的知识更加完善，于是你接触到CQF，也有了申硕的想法。



财务学:
金融学：货币、利率、汇率和金融市场
投资学：投资机构的证券投资
财务管理学：经济组织的投资和筹资（营利性组织 非营利性组织）


CPA
证券从业资格
保荐
ACCA，CFA
法律
电网
建筑
电气工程师

** 司法考试
民法：钟秀勇
老钟在瑞达开课，是法考培训民法界绝对的NO.1，无人可与争锋，强烈推荐，幽默风趣，博学多才，让民法不再枯燥。不过课时长一点，大家可以倍数播放视频

民事诉讼法：戴鹏
民诉推荐戴鹏，一个年轻有为的老师，但课讲的非常好，他在很多机构都开课，包括华旭、指南针等，去年我听的华旭

三国法：杨帆
国际法、国际私法、国际经济法合称“三国法”。杨帆公认是三国法里最厉害的老师，她在瑞达开课。不过国际法这两年分数不到30分

刑法：刘凤科、柏浪涛

刑事诉讼法：左宁、向高甲、杨雄
这三个老师都不错，我听的是厚大的向高甲，他会把很多知识点总结成口诀，方便记忆。

行政法和刑事诉讼法：李佳、徐金桂

商法和经济法：鄢梦萱、郄鹏恩
这两个都是女的，鄢梦萱在厚大有课，郄鹏恩在华旭、指南针都有课，我当时听的郄鹏恩，不过我看好多人都说鄢梦萱最好。
* IP address
  一、0.0.0.0

  严格说来，0.0.0.0已经不是一个真正意义上的IP地址了。它表示的是这样一个集合：所有不清楚的主机和目的网络。如果你在网络设置中设置了缺省网关，那么 Windows系统会自动产生一个目的地址为0.0.0.0的缺省路由。

  二、255.255.255.255

  限制广播地址。对本机来说，这个地址指本网段内(同一广播域)的所有主机。这个地址不能被路由器转发。


  三、127.0.0.1

  本机地址，主要用于测试。在Windows系统中，这个地址有一个别名“Localhost”。寻址这样一个地址，是不能把它发到网络接口的。除非出错，否则在传输介质上永远不应该出现目的地址为“127.0.0.1”的数据包。


  四、224.0.0.1

  组播地址，注意它和广播的区别。从224.0.0.0到239.255.255.255都是这样的地址。224.0.0.1特指所有主机， 224.0.0.2特指所有路由器。这样的地址多用于一些特定的程序以及多媒体程序。如果你的主机开启了IRDP(Internet路由发现协议，使用组播功能)功能，那么你的主机路由表中应该有这样一条路由。

  五、169.254.x.x

  如果你的主机使用了DHCP功能自动获得一个IP地址，那么当你的DHCP服务器发生故障，或响应时间太长而超出了一个系统规定的时间，Wingdows系统会为你分配这样一个地址。如果你发现你的主机IP地址是一个诸如此类的地址，很不幸，十有八九是你的网络不能正常运行了。

六、10.x.x.x、172.16.x.x～172.31.x.x、192.168.x.x

  私有地址，这些地址被大量用于企业内部网络中。一些宽带路由器，也往往使用192.168.1.1作为缺省地址。私有网络由于不与外部互连，因而可能使用随意的IP地址。保留这样的地址供其使用是为了避免以后接入公网时引起地址混乱。使用私有地址的私有网络在接入Internet时，要使用地址翻译 (NAT)，将私有地址翻译成公用合法地址。在Internet上，这类地址是不能出现的。

对一台网络上的主机来说，它可以正常接收的合法目的网络地址有三种：本机的IP地址、广播地址以及组播地址。

1）私有地址
私有地址可以自己组网时用，但不能在Internet网上用，Internet网没有这些地址的路由，有这些地址的计算机要上网必须转换成为合法的IP地址。Internet管理委员会规定如下地址段为私有地址：
  10.0.0.0～10.255.255.255
  172.16.0.0～172.31.255.255
  192.168.0.0～192.168.255.255

2）回送地址
  A类网络地址127是一个保留地址，用于网络软件测试以及本地机进程间通信，叫做回送地址（loopback address）。无论什么程序，一旦使用回送地址发送数据，协议软件立即返回之，不进行任何网络传输。含网络号127的分组不能出现在任何网络上。
应用举例：
  ●Ping 127.0.0.1,如果反馈信息失败,说明IP协议栈有错,必须重新安装TCP/IP协议。如果成功,ping本机IP地址,如果反馈信息失败,说明网卡不能和IP协议栈进行通信。
  ●可以用127.0.0.1这个地址访问本机的一些服务（如Sql Server等）。

3）广播地址
  TCP/IP规定，主机号全为"1"的网络地址用于广播之用，叫做广播地址。所谓广播，指同时向同一子网所有主机发送报文。

4）网络地址
  TCP/IP协议规定，各位全为"0"的网络号被解释成"本"网络。
由上可以看出：
  （1）含网络号127的分组不能出现在任何网络上；
  （2）主机和网关不能为该地址广播任何寻径信息。
由以上规定可以看出，主机号全"0"全"1"的地址在TCP/IP协议中有特殊含义，一般不能用作一台主机的有效地址。 



* wget
wget是一个从网络上自动下载文件的自由工具。它支持HTTP，HTTPS和FTP协议，可以使用HTTP代理. 
所谓的自动下载是指，wget可以在用户退出系统的之后在后台执行。这意味这你可以登录系统，启动一个wget下载任务，然后退出系统，wget将在后台执行直到任务完成，相对于其它大部分浏览器在下载大量数据时需要用户一直的参与，这省去了极大的麻烦。 
wget 可以跟踪HTML页面上的链接依次下载来创建远程服务器的本地版本，完全重建原始站点的目录结构。这又常被称作"递归下载"。在递归下载的时候，wget 遵循Robot Exclusion标准(/robots.txt). wget可以在下载的同时，将链接转换成指向本地文件，以方便离线浏览。 
wget 非常稳定,它在带宽很窄的情况下和不稳定网络中有很强的适应性.如果是由于网络的原因下载失败，wget会不断的尝试，直到整个文件下载完毕。如果是服务器打断下载过程，它会再次联到服务器上从停止的地方继续下载。这对从那些限定了链接时间的服务器上下载大文件非常有用。 
wget的常见用法
wget虽然功能强大，但是使用起来还是比较简单的，
基本的语法是：wget [参数列表] "URL" 用""引起来可以避免因URL中有特殊字符造成的下载出错。
下面就结合具体的例子来说明一下wget的用法。
    1、下载整个http或者ftp站点。
    wget http://place.your.url/here
    这个命令可以将http://place.your.url/here 首页下载下来。使用-x会强制建立服务器上一模一样的目录，如果使用-nd参数，那么服务器上下载的所有内容都会加到本地当前目录。 
    wget -r http://place.your.url/here
    这个命令会按照递归的方法，下载服务器上所有的目录和文件，实质就是下载整个网站。这个命令一定要小心使用，因为在下载的时候，被下载网站指向的所有地址同样会被下载，因此，如果这个网站引用了其他网站，那么被引用的网站也会被下载下来！基于这个原因，这个参数不常用。可以用-l number参数来指定下载的层次。例如只下载两层，那么使用-l 2。
    要是您想制作镜像站点，那么可以使用－m参数，例如：wget -m http://place.your.url/here
    这时wget会自动判断合适的参数来制作镜像站点。此时，wget会登录到服务器上，读入robots.txt并按robots.txt的规定来执行。
    2、断点续传。
    当文件特别大或者网络特别慢的时候，往往一个文件还没有下载完，连接就已经被切断，此时就需要断点续传。wget的断点续传是自动的，只需要使用-c参数，例如：
    wget -c http://the.url.of/incomplete/file
    使用断点续传要求服务器支持断点续传。-t参数表示重试次数，例如需要重试100次，那么就写-t 100，如果设成-t 0，那么表示无穷次重试，直到连接成功。-T参数表示超时等待时间，例如-T 120，表示等待120秒连接不上就算超时。
    3、批量下载。
    如果有多个文件需要下载，那么可以生成一个文件，把每个文件的URL写一行，例如生成文件download.txt，然后用命令：wget -i download.txt
这样就会把download.txt里面列出的每个URL都下载下来。（如果列的是文件就下载文件，如果列的是网站，那么下载首页）
    4、选择性的下载。
    可以指定让wget只下载一类文件，或者不下载什么文件。例如：
    wget -m --reject=gif http://target.web.site/subdirectory
    表示下载http://target.web.site/subdirectory，但是忽略gif文件。--accept=LIST 可以接受的文件类型，--reject=LIST拒绝接受的文件类型。
    5、密码和认证。
    wget只能处理利用用户名/密码方式限制访问的网站，可以利用两个参数：
    --http-user=USER设置HTTP用户
    --http-passwd=PASS设置HTTP密码
    对于需要证书做认证的网站，就只能利用其他下载工具了，例如curl。
    6、利用代理服务器进行下载。
    如果用户的网络需要经过代理服务器，那么可以让wget通过代理服务器进行文件的下载。此时需要在当前用户的目录下创建一个.wgetrc文件。文件中可以设置代理服务器：
    http-proxy = 111.111.111.111:8080
    ftp-proxy = 111.111.111.111:8080
    分别表示http的代理服务器和ftp的代理服务器。如果代理服务器需要密码则使用：
    --proxy-user=USER设置代理用户
    --proxy-passwd=PASS设置代理密码 
    这两个参数。
    使用参数--proxy=on/off 使用或者关闭代理。
    wget还有很多有用的功能，需要用户去挖掘。


wget的使用格式 
Usage: wget [OPTION]... [URL]...
* 用wget做站点镜像: 
wget -r -p -np -k http://dsec.pku.edu.cn/~usr_name/
# 或者
wget -m http://dsec.pku.edu.cn/~usr_name/
* 在不稳定的网络上下载一个部分下载的文件，以及在空闲时段下载 
wget -t 0 -w 31 -c http://dsec.pku.edu.cn/BBC.avi -o down.log &
# 或者从filelist读入要下载的文件列表
wget -t 0 -w 31 -c -B ftp://dsec.pku.edu.cn/linuxsoft -i filelist.txt -o down.log &
上面的代码还可以用来在网络比较空闲的时段进行下载。我的用法是:在mozilla中将不方便当时下载的URL链接拷贝到内存中然后粘贴到文件filelist.txt中，在晚上要出去系统前执行上面代码的第二条。 
* 使用代理下载 
wget -Y on -p -k https://sourceforge.net/projects/wvware/
代理可以在环境变量或wgetrc文件中设定 
# 在环境变量中设定代理
export PROXY=http://211.90.168.94:8080/
# 在~/.wgetrc中设定代理
http_proxy = http://proxy.yoyodyne.com:18023/
ftp_proxy = http://proxy.yoyodyne.com:18023/


wget各种选项分类列表
* 启动 
  -V,  --version           显示wget的版本后退出
  -h,  --help              打印语法帮助
  -b,  --background        启动后转入后台执行
  -e,  --execute=COMMAND   执行`.wgetrc'格式的命令，wgetrc格式参见/etc/wgetrc或~/.wgetrc
* 记录和输入文件 
  -o,  --output-file=FILE     把记录写到FILE文件中
  -a,  --append-output=FILE   把记录追加到FILE文件中
  -d,  --debug                打印调试输出
  -q,  --quiet                安静模式(没有输出)
  -v,  --verbose              冗长模式(这是缺省设置)
  -nv, --non-verbose          关掉冗长模式，但不是安静模式
  -i,  --input-file=FILE      下载在FILE文件中出现的URLs
  -F,  --force-html           把输入文件当作HTML格式文件对待
  -B,  --base=URL             将URL作为在-F -i参数指定的文件中出现的相对链接的前缀
       --sslcertfile=FILE     可选客户端证书
       --sslcertkey=KEYFILE   可选客户端证书的KEYFILE
       --egd-file=FILE        指定EGD socket的文件名
* 下载 
       --bind-address=ADDRESS   指定本地使用地址(主机名或IP，当本地有多个IP或名字时使用)
  -t,  --tries=NUMBER           设定最大尝试链接次数(0 表示无限制).
  -O   --output-document=FILE   把文档写到FILE文件中
  -nc, --no-clobber             不要覆盖存在的文件或使用.#前缀
  -c,  --continue               接着下载没下载完的文件
       --progress=TYPE          设定进程条标记
  -N,  --timestamping           不要重新下载文件除非比本地文件新
  -S,  --server-response        打印服务器的回应
       --spider                 不下载任何东西
  -T,  --timeout=SECONDS        设定响应超时的秒数
  -w,  --wait=SECONDS           两次尝试之间间隔SECONDS秒
       --waitretry=SECONDS      在重新链接之间等待1...SECONDS秒
       --random-wait            在下载之间等待0...2*WAIT秒
  -Y,  --proxy=on/off           打开或关闭代理
  -Q,  --quota=NUMBER           设置下载的容量限制
       --limit-rate=RATE        限定下载输率
* 目录 
  -nd  --no-directories            不创建目录
  -x,  --force-directories         强制创建目录
  -nH, --no-host-directories       不创建主机目录
  -P,  --directory-prefix=PREFIX   将文件保存到目录 PREFIX/...
       --cut-dirs=NUMBER           忽略 NUMBER层远程目录
* HTTP 选项 
       --http-user=USER      设定HTTP用户名为 USER.
       --http-passwd=PASS    设定http密码为 PASS.
  -C,  --cache=on/off        允许/不允许服务器端的数据缓存 (一般情况下允许).
  -E,  --html-extension      将所有text/html文档以.html扩展名保存
       --ignore-length       忽略 `Content-Length'头域
       --header=STRING       在headers中插入字符串 STRING
       --proxy-user=USER     设定代理的用户名为 USER
       --proxy-passwd=PASS   设定代理的密码为 PASS
       --referer=URL         在HTTP请求中包含 `Referer: URL'头
  -s,  --save-headers        保存HTTP头到文件
  -U,  --user-agent=AGENT    设定代理的名称为 AGENT而不是 Wget/VERSION.
       --no-http-keep-alive  关闭 HTTP活动链接 (永远链接).
       --cookies=off         不使用 cookies.
       --load-cookies=FILE   在开始会话前从文件 FILE中加载cookie
       --save-cookies=FILE   在会话结束后将 cookies保存到 FILE文件中
* FTP 选项 
  -nr, --dont-remove-listing   不移走 `.listing'文件
  -g,  --glob=on/off           打开或关闭文件名的 globbing机制
       --passive-ftp           使用被动传输模式 (缺省值).
       --active-ftp            使用主动传输模式
       --retr-symlinks         在递归的时候，将链接指向文件(而不是目录)
* 递归下载 
  -r,  --recursive          递归下载－－慎用!
  -l,  --level=NUMBER       最大递归深度 (inf 或 0 代表无穷).
       --delete-after       在现在完毕后局部删除文件
  -k,  --convert-links      转换非相对链接为相对链接
  -K,  --backup-converted   在转换文件X之前，将之备份为 X.orig
  -m,  --mirror             等价于 -r -N -l inf -nr.
  -p,  --page-requisites    下载显示HTML文件的所有图片
* 递归下载中的包含和不包含(accept/reject) 
  -A,  --accept=LIST                分号分隔的被接受扩展名的列表
  -R,  --reject=LIST                分号分隔的不被接受的扩展名的列表
  -D,  --domains=LIST               分号分隔的被接受域的列表
       --exclude-domains=LIST       分号分隔的不被接受的域的列表
       --follow-ftp                 跟踪HTML文档中的FTP链接
       --follow-tags=LIST           分号分隔的被跟踪的HTML标签的列表
  -G,  --ignore-tags=LIST           分号分隔的被忽略的HTML标签的列表
  -H,  --span-hosts                 当递归时转到外部主机
  -L,  --relative                   仅仅跟踪相对链接
  -I,  --include-directories=LIST   允许目录的列表
  -X,  --exclude-directories=LIST   不被包含目录的列表
  -np, --no-parent                  不要追溯到父目录
问题
在递归下载的时候，遇到目录中有中文的时候，wget创建的本地目录名会用URL编码规则处理。如"天网防火墙"会被存为"%CC%EC%CD%F8%B7%C0%BB%F0%C7%BD",这造成阅读上的

来自 <http://blog.csdn.net/endall/article/details/1571220> 



* VBA工程取消密码
Private Sub VBAPassword() '你要解保护的Excel文件路径
Filename = Application.GetOpenFilename("Excel文件（*.xls & *.xla & *.xlt）,*.xls;*.xla;*.xlt", , "VBA破解")
If Dir(Filename) = "" Then
MsgBox "没找到相关文件,清重新设置。"
Exit Sub
Else
FileCopy Filename, Filename & ".bak" '备份文件。
End If
Dim GetData As String * 5
Open Filename For Binary As #1
Dim CMGs As Long
Dim DPBo As Long
For i = 1 To LOF(1)
Get #1, i, GetData
If GetData = "CMG=""" Then CMGs = i
If GetData = "[Host" Then DPBo = i - 2: Exit For
Next
If CMGs = 0 Then
MsgBox "请先对VBA编码设置一个保护密码...", 32, "提示"
Exit Sub
End If

Dim St As String * 2
Dim s20 As String * 1
'取得一个0D0A十六进制字串
Get #1, CMGs - 2, St
'取得一个20十六制字串
Get #1, DPBo + 16, s20
'替换加密部份机码
For i = CMGs To DPBo Step 2
Put #1, i, St
Next
'加入不配对符号
If (DPBo - CMGs) Mod 2 <> 0 Then
Put #1, DPBo + 1, s20
End If
MsgBox "文件解密成功......", 32, "提示"
Close #1
End Sub


For a .xlsm or .dotm file type you need to do it a slightly different way.
	1. Change the extension of the .xlsm file to .zip.
	2. Open the .zip file (with WinZip or WinRar etc) and go to the xl folder.
	3. Extract the vbaProject.bin file and open it in a Hex Editor (I use HxD, its completely free and lightweight.)
	4. Search for DPB and replace with DPx and save the file.
	5. Replace the old vbaProject.bin file with this new on in the zipped file.
	6. Change the file extension back to .xlsm.
	7. Open workbook skip through the warning messages.
	8. Open up Visual Basic inside Excel.
	9. Go to Tools > VBAProject Properties > Protection Tab.
	10. Put in a new password and save the .xlsm file.
	11. Close and re open and your new password will work.

From <https://stackoverflow.com/questions/1026483/is-there-a-way-to-crack-the-password-on-an-excel-vba-project/31005696#31005696> 

* 位运算应用口诀

 清零取反要用与，某位置一可用或 
若要取反和交换，轻轻松松用异或 
移位运算 
要点 1 它们都是双目运算符，两个运算分量都是整形，结果也是整形。 
    2 " < <" 左移：右边空出的位上补0，左边的位将从字头挤掉，其值相当于乘2。 
    3 ">>"右移：右边的位被挤掉。对于左边移出的空位，如果是正数则空位补0，若为负数，可能补0或补1，这取决于所用的计算机系统。 
    4 ">>>"运算符，右边的位被挤掉，对于左边移出的空位一概补上0。 
位运算符的应用 (源操作数s 掩码mask) 
(1) 按位与-- & 
1 清零特定位 (mask中特定位置0，其它位为1，s=s&mask) 
2 取某数中指定位 (mask中特定位置1，其它位为0，s=s&mask) 
(2) 按位或-- | 
    常用来将源操作数某些位置1，其它位不变。 (mask中特定位置1，其它位为0 s=s |mask) 
(3) 位异或-- ^ 
1 使特定位的值取反 (mask中特定位置1，其它位为0 s=s^mask) 
2 不引入第三变量，交换两个变量的值 (设 a=a1,b=b1) 
    目 标          操 作              操作后状态 
a=a1^b1        a=a^b              a=a1^b1,b=b1 
b=a1^b1^b1      b=a^b              a=a1^b1,b=a1 
a=b1^a1^a1      a=a^b              a=b1,b=a1 
二进制补码运算公式： 
-x = ~x + 1 = ~(x-1) 
~x = -x-1 
-(~x) = x+1 
~(-x) = x-1 
x+y = x - ~y - 1 = (x |y)+(x&y) 
x-y = x + ~y + 1 = (x |~y)-(~x&y) 
x^y = (x |y)-(x&y) 
x |y = (x&~y)+y 
x&y = (~x |y)-~x 
x==y:    ~(x-y |y-x) 
x!=y:    x-y |y-x 
x < y:    (x-y)^((x^y)&((x-y)^x)) 
x <=y:    (x |~y)&((x^y) |~(y-x)) 
x < y:    (~x&y) |((~x |y)&(x-y))//无符号x,y比较 
x <=y:    (~x |y)&((x^y) |~(y-x))//无符号x,y比较 
应用举例 
(1) 判断int型变量a是奇数还是偶数            
a&1  = 0 偶数 
      a&1 =  1 奇数 
(2) 取int型变量a的第k位 (k=0,1,2……sizeof(int))，即a>>k&1 
(3) 将int型变量a的第k位清0，即a=a&~(1 < <k) 
(4) 将int型变量a的第k位置1， 即a=a |(1 < <k) 
(5) int型变量循环左移k次，即a=a < <k |a>>16-k  (设sizeof(int)=16) 
(6) int型变量a循环右移k次，即a=a>>k |a < <16-k  (设sizeof(int)=16) 
(7)整数的平均值 
对于两个整数x,y，如果用 (x+y)/2 求平均值，会产生溢出，因为 x+y 可能会大于INT_MAX，
但是我们知道它们的平均值是肯定不会溢出的，我们用如下算法： 
int average(int x, int y)  //返回X,Y 的平均值 
{    
    return (x&y)+((x^y)>>1); 
} 
(8)判断一个整数是不是2的幂,对于一个数 x >= 0，判断他是不是2的幂 
boolean power2(int x) 
{ 
    return ((x&(x-1))==0)&&(x!=0)； 
} 
(9)不用temp交换两个整数 
void swap(int x , int y) 
{ 
    x ^= y; 
    y ^= x; 
    x ^= y; 
} 
(10)计算绝对值 
int abs( int x ) 
{ 
int y ; 
y = x >> 31 ; 
return (x^y)-y ;        //or: (x+y)^y 
} 
(11)取模运算转化成位运算 (在不产生溢出的情况下) 
        a % (2^n) 等价于 a & (2^n - 1) 
(12)乘法运算转化成位运算 (在不产生溢出的情况下) 
        a * (2^n) 等价于 a < < n 
(13)除法运算转化成位运算 (在不产生溢出的情况下) 
        a / (2^n) 等价于 a>> n 
        例: 12/8 == 12>>3 
(14) a % 2 等价于 a & 1        
(15) if (x == a) x= b; 
　　          else x= a; 
　　      等价于 x= a ^ b ^ x; 
(16) x 的 相反数 表示为 (~x+1) 


实例 

| 功能                  | 示例                   | 位运算              |               |
|-----------------------+------------------------+---------------------+---------------|
| 去掉最后一位          | (101101->10110)        | x >> 1              |               |
| 在最后加一个0         | (101101->1011010)      | x < < 1             |               |
| 在最后加一个1         | (101101->1011011)      | x < < 1+1           |               |
| 把最后一位变成1       | (101100->101101)       | x                   | 1             |
| 把最后一位变成0       | (101101->101100)       | x                   | 1-1           |
| 最后一位取反          | (101101->101100)       | x ^ 1               |               |
| 把右数第k位变成1      | (101001->101101,k=3)   | x                   | (1 < < (k-1)) |
| 把右数第k位变成0      | (101101->101001,k=3)   | x & ~ (1 < < (k-1)) |               |
| 右数第k位取反         | (101001->101101,k=3)   | x ^ (1 < < (k-1))   |               |
| 取末三位              | (1101101->101)         | x & 7               |               |
| 取末k位               | (1101101->1101,k=5)    | x & ((1 < < k)-1)   |               |
| 取右数第k位           | (1101101->1,k=4)       | x >> (k-1) & 1      |               |
| 把末k位变成1          | (101001->101111,k=4)   | x                   | (1 < < k-1)   |
| 末k位取反             | (101001->100110,k=4)   | x ^ (1 < < k-1)     |               |
| 把右边连续的1变成0    | (100101111->100100000) | x & (x+1)           |               |
| 把右起第一个0变成1    | (100101111->100111111) | x                   | (x+1)         |
| 把右边连续的0变成1    | (11011000->11011111)   | x                   | (x-1)         |
| 取右边连续的1         | (100101111->1111)      | (x ^ (x+1)) >> 1    |               |
| 去掉右起第一个1的左边 | (100101000->1000)      | x & (x ^ (x-1))     |               |
判断奇数      (x&1)==1 
判断偶数 (x&1)==0        

例如求从x位（高）到y位（低）间共有多少个1 

public static int FindChessNum(int x, int y, ushort k) 
        { 
            int re = 0; 
            for (int i = y; i <= x; i++) 
            { 
                re += ((k >> (i - 1)) & 1); 
            } 
            return re; 
        } 
* 国际货款的支付方法
国际快递的支付方法主要有汇付、托收和信用证方式，以信用证方式使用最为普遍。在实际业务中，一般可以单独使用某种支付方式，也可以视需要将各种支付方式结合使用。 
** 一、汇付（Remittance） 
   汇付（Remittance）又称汇款，是指付款人主动将货款通过银行付给出口人。买方在汇款时可以采取三种不同的方式： 
 （一）信汇（Mail  Transfer，简称M/T） 
   信汇是指进口人（汇款人）将货款交给本地银行（汇出行），由汇出行用信承委托出口人所在地银行（汇入行）付款给出口人（收款人）。 
 （二）电汇（Telegraphic  Transfer,，简称 T/T） 
   电汇是指进口人要求本地银行以电报或电传委托出口人所在地银行付款给出口人。采用电汇方式其费用高于信汇，但出口人可以迅速收到货款。 
 （三）票汇（Demand  Draft，简称D/D） 
   票汇是指进口人向本地银行购买银行汇票，自行寄给出口人，出口人凭以向汇票上指定的银行（一般是汇出行的分行或代理行）取款的一种汇款方式。 
   汇付除按采用工具的不同分为上述三种方式外，按时间的不同又分为预付货款和货到付款两种情况： 
      1．预付货款（Payment  in  Advance） 
   预付货款是进口商先将货款的一部分或全部汇交出口商，出口商在收到货款后在规定时间内发运货物。 
      2．货到付款（Payment  after  Arrival  of  Goods） 
   货到付款是指出口商先将货物发运，进口商在收到全部合格的货物后才支付货款。 
   汇付方式评价 
   汇付是一种简便、快速的支付方式，但汇付方式的使用，完全取决于进出口双方的相互信任，因此属于商业信用。在汇付方式下，卖方在收到货款后是否交货，买方在收到货物后是否付款，完全靠买卖双方的商业信用。可见，这种支付方式下，总存在着一方要冒占压资金、损失利益、并承担货、款两空的风险。快递公司国际贸易中，这种方式主要用于预付货款、支付定金、分期付款、延期付款、小额交易的支付货款、待付货款的尾数、费用差额的支付以及佣金的支付等。 
** 二、托收（Collection） 
   托收是指债权人（出口人）出具汇票委托银行向债务人（进口人）收取货款的一种支付方式。 
 （一）托收方式的当事人 
      1．委托人（Principal）。是指委托银行办理托收业务的客户，通常是出口人。 
      2．托收银行（Remitting  Bank）。是指接受委托人的委托，办理托收业务的银行。 
      3．代收银行（Collecting  Bank）。是指接受托收行的委托向付款人收取票款的进口地银行。代收银行通常是托收银行的国外分行或代理行。 
      4．提示行（Presenting  Bank）。是指向付款人做出提示汇票和单据的银行。 
 （二）托收的种类 
   托收可根据所使用的汇票的不同，分为光票托收和跟单托收，国际贸易中货款的收取大多采用跟单托收。在跟单托收情况下，根据交单条件的不同，又可分为付款交单和承兑交单两种： 
      1．付款交单（Documents against Payment，简称D/P）。 
   是指出口人的交单是以进口人的付款为条件。即出口人发货后，取得装运单据，委托银行办理托收，并在托收书中指示银行，只有在进口人付清货款后，才能把装运单据交给进口人。 
   按付款时间的不同，付款交单又可分为即期付款交单和远期付款交单两种： 
      （1）即期付款交单（Documents  against Payment  at  sight，简称D/P  sight） 
   是指出口人发货后开具即期汇票连同货运单据，通过银行向进口人提示，进口人见票后立即付款，进口人在付清货款后向银行领取货运单据。 
      （2）远期付款交单（Documents  against  Payment  after  sight，简称D/P  after  sight） 
   是指出口人发货后开具远期汇票连同货运单据，通过银行向进口人提示，进口人审核无误后即在汇票上进行承兑，于汇票到期日付清货款后再领取货运单据。 
      2．承兑交单（Documents against Acceptance，简写D/A） 
   是指出口人的交单以进口人在汇票上承兑为条件。即出口人在装运货物后开具远期汇票，连同货运单据，通过银行向进口人提示，进口人承兑汇票后，代收银行即将货运单据交给进口人在汇票到期时，方履行付款义务。承兑交单方式只适用于远期汇票的托收。由于承兑交单是进口人只要在汇票上承兑之后，即可取得货运单据，凭以提取货物。也就是说，出口人已交出了物权凭证，其收款的保障依赖进口人的信用，一旦进口人到期不付款，出口人便会遭到货物与货款全部落空的损失。因此，出口人对接受这种方式，一般采用很慎重的态度。 
 （三）托收的性质和利弊 
   托收的性质为商业信用。银行办理托收业务时，只是按委托人的指示办事，并无承担付款人必然付款的义务。 
   跟单托收对出口人虽有一定的风险，但对进口人却很有利，他不但可免去申请开立信用证的手续，不必预付银行押金，减少费用支出，而且有利于资金融通和周转。由于托收对进口商有利，所以在出口业务中采用托收，有利于调动进口商采购货物的积极性，从而有利于促进成交和扩大出口，故许多出口商都把采用托收作为推销库存货和加强对外竞销的手段。 
 （四）托收的国际惯例 
   是国际商会的《托收统一规则》（Uniform  Rules  for  Collection  Publication  No.522）(即522出版物)，现行的规则于1996年1月1日起实施。 
   使用托收方式应注意的问题： 
      1．要切实了解进口人的资信情况和经营作风； 
      2．了解进口国家的贸易管制和外汇管制条例； 
      3．了解进口国家的商业惯例； 
      4．出口合同应争取CIF条件成交； 
      5．对托收方式的交易，要建立健全的管理制度。 
** 三、信用证 
 （一）信用证的含义 
   信用证L/C（Letter  of  Credit）是开证银行根据开证申请人的请求和指示，向受益人开立的在一定金额和一定期限内凭规定的单据承诺付款的凭证。简言之，信用证就是银行开立的一种有条件的承诺付款的书面文件。这里的条件是指受益人必须提交符合信用证规定的各种单据。 
 （二）信用证的当事人 
      1．开证申请人（Applicant）又称开证人（Opener）。 
      2．开证银行（Issuing  Bank）。 
      3．通知银行（Advising  Bank）。 
      4．受益人（Beneficiary）。 
      5．议付银行（Negotiating  Bank）。 
      6．付款银行（Paying  Bank）。 
 （三）信用证支付的一般程序 
      1．申请开立信用证：进口人按合同规定向当地银行提出申请，并交付押金或提供其他担保，要求银行（开证行）向出口人开出信用证。 
      2．开立信用证：开证行接受进口人的开证申请后，开出信用证，将信用证正本寄给出口人所在地的分行或代理行（通知行）。 
      3．通知或转递信用证：通知行将信用证转给出口人（受益人）。 
      4．议付：出口人接到信用证后，认真核对是否符合合同，如发现不符，可以要求进口人通过开证行修改，或根本拒收信用证。如信用证无误，出口人即据此进行装货及准备齐全的单据。出口人将单据和信用证交往来银行议付或交开证银行指定的代付、议付或保兑银行要求付款。代付、议付或保兑银行在审查单据符合信用证后，即预垫款项或付款，如发现单证不符，则可拒收。
      5．代付、议付或保兑行接受单据后，应在信用证背面注销所付金额(即背批)，并将单据寄送开证银行或其指定的收件人，同时向开证银行或其指定的代偿付银行索偿。单据通常分正副两批先后寄发，以免中途遗失。
      6．开证行收到单据时，要核对是否符合信用证，如无错误，即对出口人或
代付、议付或保兑行等付款，同时通知进口人付款赎单。 
 （四）信用证的主要内容 
      1．对信用证本身的说明：信用证的种类、编号、金额、有效期、到期地点，信用证有关当事人的名称、地址等。 
      2．对货物的记载：货物名称、规格、牌号、数量、包装、单价、唛头等。 
      3．装运条款：包括运输方式、装运港（地）、目的港（地）、装运日期、是否分批装运或转船等。 
      4．对单据的要求：规定应附哪些单据及对有关单据的具体要求和应出具的份数。 
      5．特殊条款：一般书写在背面，规定交单日期或者要求某一特殊单据。 
      6．责任文句：开证行对受益人即汇票持有人保证付款的责任文句。 
 （五）信用证的特点 
   根据《跟单信用证统一惯例》的规定，信用证主要有以下几个特点：
      1．信用证是一种银行信用。
   信用证支付方式是以银行信用作保证的，因此，开证行应承担第一性的付款责任。按《跟单信用证统一惯例》的规定，在信用证业务中，开证行对受益人的付款责任是首要的、独立的。即使开证人事后丧失偿付能力，只要出口人提交的单据符合信用证条款，开证行也必须承担付款责任。
      2．信用证是一项自足的文件。
   信用证是依据买卖合同开立的，但一经开立，即成为独立于买卖合同之外的契约。信用证各当事人的权利和责任完全以信用证条款为依据，不受买卖合同的约束。
      3．信用证是一种单据的买卖。
   信用证业务是“单据业务”。银行处理信用证业务只凭单据，不问货物的真实状况如何。银行以受益人提交的单据是否与信用证条款相符为依据，决定是否付款。如开证行拒付，也必须以单据上的不符点为由。这种“相符”必须是“严格符合”，不仅要单证一致，而且还要求单单一致。
 （六）信用证的种类 
      1．根据是否有货运单据，分为跟单信用证和光票信用证：
   跟单信用证(Documentary  Credit)是凭跟单汇票或仅凭单据付款的信用证。单据是指代表货物所有权或证明货物已交运的单据。光票信用证(Clean  Credit)是指凭不附单据的汇票付款的信用证。国际贸易中通常使用的都是跟单信用证。
  2．根据开证行所负责任的不同，分为可撤销信用证和不可撤销信用证。
可撤销信用证(Revocable  Letter  of  Credit)是指开证银行可以不经受益人同意，也不必事先通知受益人，在议付银行议付之前有权随时取消或修改的信用证。这种信用证对受益人缺乏保障，所以在实际业务中不常采用。不可撤销信用证(Irrevocable  Letter  of  Credit)是指信用证一经开出，在其有效期内，若未经受益人及有关当事人的同意，开证行不得片面修改或撤销的信用证。只要受益人提供的单据符合信用证规定，开证行就必须履行付款义务。这种信用证上都明确注有“不可撤销”字样。由于这种信用证的银行信用程度高，受益人权利较有保障，故为外商投资企业所采用。
      3．根据信用证有无其它银行保兑，分为保兑信用证和不保兑信用证。
   保兑信用证(Confirmed  L／C)是指出口人为了保证安全收汇，要求开证银行开出的信用证必须经另一家银行保证兑付。对信用证加以保兑的银行叫保兑行。保兑行一经保兑，就承担和开证银行同样的付款责任。保兑行通常是通知行，有时也可以是出口地的其他银行或第三国银行。未经另一家银行加具保兑的信用证就是不保兑信用证(Unconfirmed  L／C)。
      4．根据付款时间的不同，可分为即期信用证和远期信用证。
   即期信用证(Sight L／C)是单到付款的信用证。即开证行或付款行收到符合信用证条款的跟单汇票和装运单据后，立即付款。这是在国际货款结算时普遍使用的一种信用证。远期信用证(Unasked  L／C)是指开证行在收到符合信用证条款规定的汇票和单据后，不立即付款，而是办理承兑手续，待远期汇票到期后再付款。
      5．根据运用方式的不同，分为可转让信用证、不可转让信用证和循环信用证。
   可转让信用证(Transferable  l／C)指开证行开立的写明“可转让”字样、受益人可以全部或部分转让给第二受益人的信用证。可转让信用证只能转让一次，转让费由第一受益人负责，但可同时转让给一个或一个以上的第二受益人。凡信用证上未注明““可转让”字样，即受益人不能将信用证的权利转让给他人的信用证，都是不可转让信用证(Non—transferable  L／C)，实际业务中多数是这种信用证。
   循环信用证(Revolving L／C)是指当受益人全部或部分用完信用证内的金额后，其金额能恢复到原金额，而再次被受益人使用，甚至可以多次使用，直至达到规定次数或累计总金额为止。循环信用证与一般信用证的不同之处就在于前者可多次循环使用，而后者则在一次使用后即告失效。循环信用证适用于分批均匀交货的长期供货合同。
 （七）信用证的国际惯例 
   国际商会于1951年、1962年、1974年、1983年和1993年相继对《商业跟单信用证统一惯例》进行了修改，现行的《跟单信用证统一惯例》称为国际商会第500号出版物，于1994年1月实施。 
** 四、银行保证书 
 （一）银行保证书的含义 
   银行保证书（Letter  of  Guarantee,简称L/G）又称保函，是指银行、保险公司、担保公司或个人（保证人）应申请人的请求，向第三方（受益人）开立的一种书面信用担保凭证。保证人对申请人的债务或应履行的义务，承担赔偿责任。 
见索即付保函和有条件保函。 
 （二）银行保证书的种类 
   银行保证书按其用途可分为投标保证书、履约保证书和还款保证书三种： 
      1．投标保证书（Tender  Guarantee） 
      2．履约保证书（Performance  Guarantee） 
      3．还款保证书（Repayment  Guarantee） 
 （三）银行保证书的主要内容 
      1．有关当事人 
      2．责任条款 
      3．保证书的有效期 
      4．保证书的终止到期日 
      5．保证书的修改 
** 五、各种支付方式的选用 
 （一）信用证与汇付相结合 
   这种方式具体有两种做法：
   一是部分货款采用信用证方式付款，余额用汇付方式结算。即进口商首先开信用证支付发票金额的若干成，余数部分待货物到达目的地后，根据检验结果计算出确切金额，另以汇付的方式支付。采用这种方法时，应明确规定使用何种信用证和何种汇付方式，以及采用信用证付款的比例，以防出现争议和纠纷。
   二是先汇付部分货款，余额部分在出口商发货时由进口商开立信用证支付。这主要用于须先付预订金的交易(如成套设备的交易)，进口商成交时须交纳的订金以汇付方式支付，余额部分以信用证支付。
 （二）信用证与托收相结合
   这种方式是部分货款以信用证支付，余额部分以托收方式支付。采用这种做法时，发票和其他单据并不分开，仍按全部货款金额填制，只是出口人须签发两张汇票，分别用于信用证项下和托收项下。为减少风险，一般信用证项下部分的货款为光票支付，托收采用跟单托收方式。此外，还可在信用证中规定，只有在进口商付讫了托收项下的汇票后，开证行方可交单。这种做法既减少了进口商的开证费用，又使出口商的收汇有一定的安全保障，故受到进出口双方的欢迎。

* C++
范型编程与 STL       STL 源码剖析
Ｃ++关键词
asm，auto，bad_cast，bad_typed，bool，break，case，catch，char，class，const，const_cast，continue，default，delete，do，double，dynamic_cast，else，enum，except，extern，explicit，false，finally，float，for，friend，goto，if，inline，int，long，mutable，namespace，new，operator，private，protected，public，register，reinterpret_cast，return，short，signed，sizeof，static，static_cast，struct，switch，template，this，throw，try，type_info，typedef，typeid，union，unsigned，using，virtual，void，volatile，while

Ｃ++还有12个标识符作为编译预处理
define，elif，else，endif，error，if，ifdef，ifndef，include，line，progma，undef 

C++的标点和特殊字符有
!  %  ^  &  *  (  )  –  +  =  {  }  |  ~
[  ]  \  ;  '  :  "  <  >  ?  ,  .  /  #

字符型      	char                   1B
短整数      	short                  2B
整型          	int                    4B
浮点型      	float                  4B
双精度型  	double                 8B

赋值运算< ||<&& <  关系运算 <  算术运算< ！

* Shell
1.命令行日常系快捷键
如下的快捷方式非常有用，能够极大的提升你的工作效率：
CTRL + U -剪切光标前的内容
CTRL + K -剪切光标至行末的内容
CTRL + Y -粘贴
CTRL + E -移动光标到行末
CTRL + A -移动光标到行首
ALT + F -按单词前移（右向）
ALT + B -按单词后移（左向）
ALT + Backspace -删除前一个单词
CTRL + W -从光标处删除至字首
Shift + Insert -向终端内粘贴文本
2. SUDO !!
sudo !!就会用sudo的形式运行上一条命令。所以上一条命令就变成了这样：

3.暂停并在后台运行命令
我曾经写过一篇如何在终端后台运行命令的指南。
CTRL + Z -暂停应用程序
fg -重新将程序唤到前台
如何使用这个技巧呢?
试想你正用nano编辑一个文件：
sudo nano abc.txt文件编辑到一半你意识到你需要马上在终端输入些命令，但是nano在前台运行让你不能输入。
你可能觉得唯一的方法就是保存文件，退出nano，运行命令以后在重新打开nano。
其实你只要按CTRL + Z，前台的命令就会暂停，画面就切回到命令行了。然后你就能运行你想要运行命令，等命令运行完后在终端窗口输入“fg”就可以回到先前暂停的任务。
有一个尝试非常有趣就是用nano打开文件，输入一些东西然后暂停会话。再用nano打开另一个文件，输入一些什么后再暂停会话。如果你输入“fg”你将回到第二个用nano打开的文件。只有退出nano再输入“fg”，你才会回到第一个用nano打开的文件。
4.使用nohup在登出SSH会话后仍运行命令
如果你用ssh登录别的机器时，nohup命令真的非常有用。
那么怎么使用nohup呢？
想象一下你使用ssh远程登录到另一台电脑上，你运行了一条非常耗时的命令然后退出了ssh会话，不过命令仍在执行。而nohup可以将这一场景变成现实。
举个例子，因为测试的需要，我用我的树莓派来下载发行版。我绝对不会给我的树莓派外接显示器、键盘或鼠标。
一般我总是用SSH从笔记本电脑连接到树莓派。如果我在不用nohup的情况下使用树莓派下载大型文件，那我就必须等待到下载完成后，才能登出ssh会话关掉笔记本。可如果是这样，那我为什么要使用树莓派下文件呢？
使用nohup的方法也很简单，只需如下例中在nohup后输入要执行的命令即可：
nohup wget http://mirror.is.co.za/mirrors/linuxmint.com/iso//stable/17.1/linuxmint-17.1-cinnamon-64bit.iso &
5.‘在’特定的时间运行Linux命令
‘nohup’命令在你用SSH连接到服务器，并在上面保持执行SSH登出前任务的时候十分有用。
想一下如果你需要在特定的时间执行相同的命令，这种情况该怎么办呢？
命令‘at’就能妥善解决这一情况。以下是‘at’使用示例。
at 10:38 PM Friat> cowsay 'hello'at> CTRL + D上面的命令能在周五下午10时38分运行程序cowsay。
使用的语法就是‘at’后追加日期时间。当at>提示符出现后就可以输入你想在那个时间运行的命令了。
CTRL + D返回终端。
还有许多日期和时间的格式，都需要你好好翻一翻‘at’的man手册来找到更多的使用方式。
6. Man手册
Man手册会为你列出命令和参数的使用大纲，教你如何使用她们。Man手册看起来沉闷呆板。（我思忖她们也不是被设计来娱乐我们的）。
不过这不代表你不能做些什么来使她们变得漂亮些。
export PAGER=most你需要安装‘most’；她会使你的你的man手册的色彩更加绚丽。
你可以用以下命令给man手册设定指定的行长：
export MANWIDTH=80最后，如果你有一个可用的浏览器，你可以使用-H在默认浏览器中打开任意的man页。
man -H 注意啦，以上的命令只有在你将默认的浏览器设置到环境变量$BROWSER中了之后才效果哟。
7.使用htop查看和管理进程
你用哪个命令找出电脑上正在运行的进程的呢？我敢打赌是‘ps’并在其后加不同的参数来得到你所想要的不同输出。
安装‘htop’吧！绝对让你相见恨晚。
htop在终端中将进程以列表的方式呈现，有点类似于Windows中的任务管理器。你可以使用功能键的组合来切换排列的方式和展示出来的项。你也可以在htop中直接杀死进程。
在终端中简单的输入htop即可运行。
htop
8.使用ranger浏览文件系统
如果说htop是命令行进程控制的好帮手，那么ranger就是命令行浏览文件系统的好帮手。
你在用之前可能需要先安装，不过一旦安装了以后就可以在命令行输入以下命令启动她：
ranger在命令行窗口中ranger和一些别的文件管理器很像，但是相比上下结构布局，她是左右结构的，这意味着你按左方向键你将前进到上一个文件夹，而右方向键则会切换到下一个。
在使用前ranger的man手册还是值得一读的，这样你就可以用快捷键操作ranger了。
9.取消关机
无论是在命令行还是图形用户界面关机后，才发现自己不是真的想要关机。
shutdown -c需要注意的是，如果关机已经开始则有可能来不及停止关机。
以下是另一个可以尝试命令：
pkill shutdown
10.杀死挂起进程的简单方法
想象一下，你正在运行的应用程序不明原因的僵死了。
你可以使用‘ps -ef’来找到该进程后杀掉或者使用‘htop’。
有一个更快、更容易的命令叫做xkill。
简单的在终端中输入以下命令并在窗口中点击你想杀死的应用程序。
xkill那如果整个系统挂掉了怎么办呢？
按住键盘上的‘alt’和‘sysrq’不放，然后慢慢输入以下键：
REISUB
这样不按电源键你的计算机也能重启了。

查看当前发行版可以使用的shell
[jack@localhost ~]$ cat /etc/shells 
/bin/sh
/bin/bash
/sbin/nologin
查看当前使用的shell
一、最常用的查看shell的命令，但不能实时反映当前shell
[jack@localhost ~]$ echo $SHELL
/bin/bash
二、下面这个用法并不是所有shell都支持
[jack@localhost ~]$ echo $0
bash
三、环境变量中shell的匹配查找
[jack@localhost ~]$ env | grep SHELL
SHELL=/bin/bash
四、口令文件中shell的匹配查找
[jack@localhost ~]$ cat /etc/passwd | grep jack
jack:x:500:500:mengfei:/home/jack:/bin/bash
五、查看当前进程
[jack@localhost ~]$ ps
PID TTY          TIME CMD
3052 pts/0    00:00:00 bash
3254 pts/0    00:00:00 ps
六、先查看当前shell的pid，再定位到此shell进程
[jack@localhost ~]$ echo $$
3052
[jack@localhost ~]$ ps -ef | grep 3052
jack        3052 3047 0 11:33 pts/0    00:00:00 bash
jack        3420 3052 0 11:57 pts/0    00:00:00 ps -ef
jack        3421 3052 0 11:57 pts/0    00:00:00 grep 3052
附：一条命令即可实现：
[jack@localhost ~]$ ps -ef | grep `echo $$` | grep -v grep | grep -v ps
jack        3052 3047 0 11:33 pts/0    00:00:00 bash

七、输入一条不存的命令，查看出错的shell提示
[jack@localhost ~]$ tom
bash: tom: command not found

来自 <http://www.cnblogs.com/zfc2201/articles/6032292.html> 

* git gcc
git clone git://gcc.gnu.org/git/gcc.git

* 新VPS设置记录
1 更新系统
2 安装 python-pip （apt）
3  安装 shadowshocks-liev（apt）
4 安装 emacs

apt-get install python-pip shadowsocks emacs fish texlive

5  设置 /etc/shadowsocks/config.json
	
	{
	    "server":"139.59.44.4",
	    "server_port":8388,
	    "local_address": "127.0.0.1",
	    "local_port":1080,
	    "password":"myvpn123",
	    "timeout":300,
	    "method":"aes-256-cfb",
	    "fast_open": false,
	    "workers": 1
	}
	
	
	多用户
	{
		"server":"0.0.0.0",
		"local_port":1080,
		{
			"port_password":{
				"13839":"abcde1",
				"12179":"abcde2",
				"16713":"abcde3",
				"18711":"abcde4",
				"17739":"abcde5"
		},
		"method":"aes-256-cfb",
		"timeout":600
	} 
	
	
6  设置ss后台运行 sudo 
	ssserver -c /etc/shadowsocks/config.json -d start
	
7 新建用户 adduser xurong
8  新建sudo权限 使用visudo C-o保存 C-x退出 保存文件名为/etc/sudoers
c  git ssh设置 
	ssh-keygen -t rsa -C "xurong@foxmail.com"

	git config --global push.default simple
	git config --global user.email "xurong@foxmail.com"
	git config --global user.name xurong



dpkg --get-selections > /home/user/package.selections

sudo dpkg --set-selections package.selections && apt-get dselect-upgrade



Vultr_Tokyo 
IP:45.77.22.221  Port:23
Root: Fp6!nH?qcJB9aJmM

新建用户 adduser userID
使用visudo新增root权限
安装桌面环境（apt-get install xunbuntu-desktop）
apt-get install xrdp 
apt-get install vnc4server tightvncserver

安装完毕以后，执行以下命令
service xrdp restart

在root目录下新建一个文件.xsession文件。
内容为:

xfce4-session


即可使用windows下的remote连接

安装Recordmydesktop和Reminna远程桌面客户端
Recordmydesktop让你能够录制在Kali Linux中的活动，并制作视频。Remmina类似Windows远程桌面客户端。两者都非常实用。可以使用下面这个命令安装它们：
apt-get install gtk-recordmydesktop recordmydesktop remmina -y 

安装GDebi程序包管理器
dpkg是一个功能强大的工具，但它并不自动安装依赖项。为此，我们需要某种程序包安装工具，以便在安装.deb程序包的同时，可以去获取所有必要的依赖项。眼下最出色的程序包安装工具非gdebi莫属。使用下面这个命令来安装它：
apt-get install gdebi -y 

* VPS
了解shadowsocks原理的预备知识：
 1. HTTP: The Definitive Guide 
2. TCP/IP Illustrated 
3. Stanford 的 Cryptography http://online.stanford.edu/course/cryptography
2017年10月2日
10:45
1、完成 MIT 6.00.1x
2、How to Design Programs, Second Edition
3、SICP
4、The Elements of Computing Systems
5、Computer Systems: A Programmer's Perspective, 3/E《深入理解计算机系统》

Sicp
	How to design Programs 2nd edition
	
The elements of computing systems

深入理解计算机系统：形成：网络->内存->缓存->CPU

C programming language

UNIX编程环境


算法导论：（数据结构与算法分析 比较简单）

结合SICP   看编程珠玑     程序设计实践

编程语言基础：1、C++        C++ Primer->effective C++ ->C ++  templates->the design and ecehngvolution of c++
			     2、程序设计语言--实践之路
			      3、coursera 课程 MOOC
				4、udacity cs262 Programming language
				5、用python 写一个scheme interpreter
